#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].system_twn > "/dev/null"; then
	uci -q batch <<-EOF
		set system.@system[0].timezone="CST-8"
		set system.@system[0].zonename="Asia/Taipei"

		delete system.ntp.server
		add_list system.ntp.server="time.google.com"
		add_list system.ntp.server="time.cloudflare.com"

		set system.@imm_init[0].system_twn="1"
		commit system
	EOF
fi

sed -i.bak "s,downloads.immortalwrt.org,mirrors.vsean.net/openwrt,g" "/etc/opkg/distfeeds.conf"

exit 0
